### ISSUE TITLE
A specific question

### ISSUE THREAD

**Issue by vdecristofaro** [KevinDockx/DocumentingAspNetCoreApisWithOpenAPI#2]
Hello,
Just followed your pluralsight course and found it very interesting. Well explained and very good example summarized in this repository. 

I am using a setup which has been detailed into issue [#1024](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1024) at swashbuckle repo. 

However I am not able to resolve the limit encountered in that setup. Would be too much to ask for your opinion? 

Thanks a lot.

**Comment by KevinDockx** [comment]
Just had a look at that question - that's a very interesting setup, seems like you've got most of it figured out already :)  I'm afraid I don't have experience with what you're asking, but as IApiDescriptionGroupCollectionProvider is part of ASP.NET Core itself, you can find out how/when it gets populated by having a look at Core's source code; these are the references to it I found: https://github.com/aspnet/AspNetCore/search?q=IApiDescriptionGroupCollectionProvider&unscoped_q=IApiDescriptionGroupCollectionProvider 

Hope this helps!
